site_name: XYZ Garden
theme: 
  name: material
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
  
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
 
  features:
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - autolinks
  - roamlinks 

nav:
  - Home:
    - index.md
  - 3D-Fundamentals:
    - 3D-Fundamentals/index.md
    